[MY_HTOP_PATH]
# Path to the NPU load file
npu_load_path = /sys/kernel/debug/rknpu/load
# Path to the NPU frequency file
npu_freq_path = /sys/class/devfreq/fdab0000.npu/cur_freq
# Path to the GPU load file
gpu_load_path = /sys/class/devfreq/fb000000.gpu-panthor/load
# Path to the GPU frequency file
gpu_freq_path = /sys/class/devfreq/fb000000.gpu-panthor/cur_freq
# Path to the CPU frequency files (pattern)
cpu_freq_pattern = /sys/devices/system/cpu/cpu{core}/cpufreq/scaling_cur_freq

[MODE]
benchmark_mode = false

[INFERENCE]
# Set to 'NPU' or 'CPU'
device = NPU

[PATHS]
model_rknn = assets/models/ARDS2_1-640-640-yolov11n.rknn
model_onnx = assets/models/ARDS2_1-640-640-yolov11n.onnx
model_labels = assets/models/ARDS2_1-640-640-yolov11n-labels.txt
benchmark_video = assets/videos/Shooting046_x264.mp4

[IMAGE]
img_width = 640
img_height = 640
fps_text_size = 0.5
label_text_size = 0.4

[CAMERA]
max_cameras_to_scan = 6

[CLASSES]
# Default labels to use if no model_labels file is provided
default_labels = person,gun,pistol,revolver,firearm,knife,machete,katana,dagger,sword,axe,bat,club,bludgeon,stick,nunchaku,shuriken,throwing star,crossbow,spear,harpoon,boomerang,slingshot,catapult,grenade,explosive device,machine gun,shotgun,assault rifle,sniper rifle,submachine gun,light machine gun,heavy machine gun,rocket launcher,missile launcher,flamethrower,taser,stun gun,pepper spray
