[MODE]
benchmark_mode = true

[INFERENCE]
# Set to 'NPU' or 'CPU'
device = NPU

[PATHS]
model_rknn = assets/models/ARDS2_1-640-640-yolov11n.rknn
model_onnx = assets/models/ARDS2_1-640-640-yolov11n.onnx
model_labels = assets/models/ARDS2_1-640-640-yolov11n-labels.txt
benchmark_video = assets/videos/benchmark.mp4

[IMAGE]
img_width = 640
img_height = 640
fps_text_size = 0.5
label_text_size = 0.4

[CAMERA]
max_cameras_to_scan = 6

[CLASSES]
# Default labels to use if no model_labels file is provided
default_labels = person,gun,pistol,revolver,firearm,knife,machete,katana,dagger,sword,axe,bat,club,bludgeon,stick,nunchaku,shuriken,throwing star,crossbow,spear,harpoon,boomerang,slingshot,catapult,grenade,explosive device,machine gun,shotgun,assault rifle,sniper rifle,submachine gun,light machine gun,heavy machine gun,rocket launcher,missile launcher,flamethrower,taser,stun gun,pepper spray
